import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="min-h-screen flex justify-center  p-24 bg-gray-200 ">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
